mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
# from django.urls import path, include
from django.urls import include

app_name = 'polls'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace='polls')),
]

polls/urls.py
from django.conf.urls import url
# from django.urls import path
# importujemy views z tego samego folderu, dlatego dajemy '.'

from . import views

app_name = 'polls'
#r'^$' = nic nie dodawaj do naszego url
urlpatterns = [
    url(r'^$', views.index, name="index"),
    #127.0.0.1:8000/polls/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name="detail"),
    #127.0.0.1:8000/polls/1
    url(r'^(?P<question_id>[0-9]+)/results$', views.results, name="results"),
    #127.0.0.1:8000/polls/1/results
    url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name="vote"),
    #127.0.0.1:8000/polls/1/vote

]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.template import loader
from django.urls import reverse

from .models import Question

# Create your views here.
#
#request function:
def index(request):
    # wywołanie pytań według parametru 'publish_date' - data publikacji (5 najnowszych)
    latest_questions = Question.objects.order_by('-publish_date')[:5]
    #wersja z plikiem html:

    template = loader.get_template('polls/index.html')
    #tutaj jest funkcja pobrania treści requesta - działa to poprzez zczytywanie treści pliku html,
    # który podajemy (dlatego render)
    context = ({
        'latest_questions':latest_questions
    })

    return HttpResponse(template.render(context))

    # #wersja bez użycia html: dodajemy przecinki między wynikami latest_questions -
    # output = ", ".join(q.question_text for q in latest_questions)
    # return HttpResponse(output)

def detail(request, question_id):
    # question = Question.objects.get(pk = question_id)

    # jeśli chcemy obsłużyć błąd, jeśli nie ma nic go pobrania (get):
    question = get_object_or_404(Question, pk = question_id)
    #inny sposób na renderowanie contextu z html:
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html',{'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
        return render(request, 'polls/detail.html', {'question':question, 'error_message': 'Please, select a choice'})
    #teraz dodajemy implementację, która zliczy nam głosy:
    else:
        selected_choice.votes += 1
        selected_choice.save()
        #teraz po wykonaniu wszystkiego chcemy włączyć result page
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/base.html
{%  load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel = "stylesheet" type= "text/css" href = "{%static 'polls/style.css' %}"/>
    <title></title>
</head>
<body>
<hr>
<p> Header </p>
<hr>

{% block main_content %}
{% endblock %}

{% include 'polls/footer.html' %}

</body>
</html>

polls/templates/polls/detail.html
{%  extends 'polls/base.html' %}

{# chcemy utworzyć blok, który będzie wklejony tam, gdzie określa to base.html #}

{% block main_content %}


{#chcemy utworzyć wyświetlenie nagłówka pytania i wybór:#}
<h1>{{ question.question_text }}</h1>

    {%  if error_message %} <p> <strong> {{ error_message}}</strong></p> {%  endif %}

    <form action = '{% url 'polls:vote' question.id %}' method = "POST">

    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value = "{{choice.id}}"/>
        <label for="choice{{ forloop.counter}}"> {{ choice.choice_text }}</label> <br>
    {% endfor %}
    <input type="submit" value="vote"/>

    </form>

    <a href="{% url 'polls:index' %}"> <- Back to question list</a>

{% endblock %}

</body>
</html>

polls/templates/polls/footer.html
<hr>
<p>Footer</p>
<hr>

polls/templates/polls/index.html
{%  extends 'polls/base.html' %}

{# chcemy utworzyć blok, który będzie wklejony tam, gdzie określa to base.html #}

{% block main_content %}

{% if latest_questions %}
    <ul>
        {%  for question in latest_questions %}
            <li><a href = {% url "polls:detail" question.id %}><b> {{ question.question_text }}</b></a></li>
{#            <li><a href = '/polls/{{question.id}}'><b> {{question.question_text}} </b></a></li>#}
        {%  endfor %}
    </ul>
{%  else %}
    <p> You don't have any questions. Please add some. </p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{%  extends 'polls/base.html' %}

{# chcemy utworzyć blok, który będzie wklejony tam, gdzie określa to base.html #}

{% block main_content %}

<h1>{{ question.question_text }}</h1>

    <ul>

    {%  for choice in question.choice_set.all %}
{#        #wyświetlamy jaki wybór#}
        <li> {{ choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    {#    wyświetlamy ilośc wyborów#}
    <a href="{% url 'polls:detail' question.id %}"> Vote again?</a>
{% endblock %}